# Redpanda Cluster for OKE (Kafka-compatible)
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: redpanda
spec:
  serviceName: redpanda
  replicas: 1  # Starting with 1 for Always Free tier constraints
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
      - name: redpanda
        image: docker.redpanda.com/redpandadata/redpanda:v23.2.15
        command:
        - "sh"
        - "-c"
        - |
          rpk redpanda start \
          --mode dev-container \
          --set redpanda.auto_create_topics_enabled=true \
          --set redpanda.enable_transactions=true \
          --set redpanda.enable_idempotence=true \
          --set redpanda.default_topic_replications=1 \
          --set redpanda.transaction_coordinator_replication=1 \
          --set redpanda.id_allocator_replication=1 \
          --set redpanda.enable_rack_awareness=false
        ports:
        - containerPort: 9092
          name: kafka-api
        - containerPort: 9644
          name: admin-api
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-cluster
  namespace: redpanda
  labels:
    app: redpanda
spec:
  selector:
    app: redpanda
  ports:
  - name: kafka-api
    port: 9092
    targetPort: 9092
  - name: admin-api
    port: 9644
    targetPort: 9644
  type: ClusterIP
---
# Redpanda Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: redpanda