# Namespace for the Todo Application
apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
---
# Secrets for the Todo Application
apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo-app
type: Opaque
data:
  # These values should be base64 encoded
  # Example: echo -n "your-value" | base64
  database-url: dmlicmFudGVzdEBuZW9uLnRlY2g=  # base64 encoded "vibrantest@neon.tech" (placeholder)
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmU=  # base64 encoded "your-secret-key-here" (placeholder)
  openai-api-key: c2tfdGVzdF95b3VyX2FwaV9rZXk=  # base64 encoded "sk_test_your_api_key" (placeholder)
---
# Dapr Configuration
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
  namespace: todo-app
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
  metric:
    enabled: true
  httpPipeline:
    handlers: []
  features:
  - name: AppHealthCheck
    enabled: true