# Namespace for the Todo Application
apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
---
# Secrets for the Todo Application
apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo-app
type: Opaque
data:
  # These values should be base64 encoded in production
  # Example values shown here for reference only
  database-url: <base64-encoded-database-url>
  secret-key: <base64-encoded-secret-key>
  openai-api-key: <base64-encoded-openai-api-key>
---
# Dapr Configuration
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
  namespace: todo-app
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
  metric:
    enabled: true
  httpPipeline:
    handlers: []
  features:
  - name: AppHealthCheck
    enabled: true